modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="cobr"
version="v0.a2c"
displayName="Civilisations of Baedoor"
credits="Toma400, DylanVHS, Poltergeist, Lyof, RiftJaw"
displayURL="https://mcreator.net/forum/76024/civilisations-baedoor-structures-npcs-and-civilisations-mod"
logoFile="logo.png"
authors="Toma400"
description='''
Wanderers of our world... new mysteries have arised, giving birth to new dimensional entrances. Some forces try to conquer the lands of Overworld.. or maybe they already succeed? Find yourself inside fight of strange civilisations that appeared in this place.
'''

[[dependencies.cobr]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




